### PR TITLE
Fixed map zoom for directions step by step and bug with transit radio button

### PR DESCRIPTION
**Pull request by MikeBrichko**
Updated map zoom for step by step directions
Fixed bug where clicking transit radio button was not displaying its list view

### CODE REVIEW

**Review by pobudzey — COMMENTED** [review]
Tested it out on my phone and the transit radio button bug is fixed
However, when clicking on the "Start" button, the camera zooms (out) on the whole route instead of zooming in on the first step. Is that intended behavior?

**Comment by MikeBrichko** [comment]
> Tested it out on my phone and the transit radio button bug is fixed
> However, when clicking on the "Start" button, the camera zooms (out) on the whole route instead of zooming in on the first step. Is that intended behavior?

**Comment by sharon-ho** [comment]
@pobudzey Tested this branch and the camera does zoom in to the first step. So I'll give this an approval.

**Review by sharon-ho — APPROVED** [review]
Step by step view is now visible.

**Pull request merged**
